// The Guess the Dish dish bank, by cuisine. Each row is
// [id, name, emoji clue, one-line hint, accepted alternative names?].
// Hints never contain the dish's own name or aliases (checked by the
// validation script in the PR). Emoji are Unicode 13 or older so they render
// on older phones; no flag emoji (Windows shows those as letters).

export type Region = "Italian" | "Asian" | "African" | "Latin American" | "North American" | "European" | "Middle Eastern";

type Row = [id: string, name: string, emoji: string, hint: string, aliases?: string[]];

export const BANK: Record<Region, Row[]> = {
  Italian: [
    ["bolognese", "Spaghetti bolognese", "🍝🥩🍅", "Long pasta strands under a slow-cooked meat and tomato ragù named after a northern Italian city.", ["spag bol", "bolognese", "spaghetti bolognaise", "bolognaise"]],
    ["margherita", "Pizza Margherita", "🍕🍅🧀🌿", "Naples' classic in the colours of the Italian flag: tomato, mozzarella and basil.", ["margherita pizza", "margherita", "pizza", "margarita pizza"]],
    ["lasagna", "Lasagna", "🧀🥩🍅🧀", "Flat pasta sheets layered with meat sauce, béchamel and cheese, then baked.", ["lasagne"]],
    ["risotto", "Risotto", "🍚🧀🍄🥄", "Short-grain rice stirred slowly with hot stock until creamy.", ["mushroom risotto"]],
    ["tiramisu", "Tiramisu", "☕🍰🍫", "Coffee-soaked sponge fingers layered with mascarpone cream and dusted with cocoa.", ["tiramisù"]],
    ["carbonara", "Spaghetti carbonara", "🍝🥓🥚🧀", "Roman pasta tossed with egg yolk, crispy cured pork cheek and pecorino - no cream.", ["carbonara", "pasta carbonara"]],
    ["alfredo", "Fettuccine Alfredo", "🍝🧈🧀", "Ribbon pasta coated in butter and parmesan, born in Rome and adored in America.", ["alfredo", "fettucine alfredo", "pasta alfredo"]],
    ["pesto", "Pesto", "🌿🧄🧀🥜", "Genoa's green sauce of pounded basil, pine nuts, garlic and parmesan.", ["pesto genovese", "pesto alla genovese", "basil pesto", "pesto pasta"]],
    ["minestrone", "Minestrone", "🥣🥕🍅🧅", "Chunky Italian vegetable soup, often with pasta or beans in it."],
    ["bruschetta", "Bruschetta", "🍞🍅🌿🧄", "Grilled bread rubbed with garlic and piled with chopped tomato and basil."],
    ["gnocchi", "Gnocchi", "🥔🧀🍅", "Soft little potato dumplings, tossed in tomato sauce or sage butter.", ["potato gnocchi"]],
    ["ravioli", "Ravioli", "🥟🍅🌿", "Square pasta pillows stuffed with cheese, spinach or meat."],
    ["osso-buco", "Osso buco", "🦴🥩🍋", "Milanese braised veal shanks with the marrow bone in, topped with lemon-zest gremolata.", ["ossobuco"]],
    ["panna-cotta", "Panna cotta", "🍮🍓", "Silky set cream dessert from Piedmont, wobbling under a berry sauce.", ["pannacotta"]],
    ["gelato", "Gelato", "🍦🍓🍫🥄", "Italy's dense, intensely flavoured ice cream, served with a little spade."],
    ["cannoli", "Cannoli", "🥖🧀🍒", "Sicilian crisp fried pastry tubes filled with sweet ricotta.", ["cannolo"]],
    ["arancini", "Arancini", "🍙🧀🔥", "Sicilian deep-fried rice balls with a molten cheese or ragù centre.", ["arancine", "arancino"]],
    ["focaccia", "Focaccia", "🍞🫒🌿", "Dimpled flat oven bread drenched in olive oil and rosemary.", ["foccacia"]],
    ["calzone", "Calzone", "🥟🍕🧀", "A pizza folded in half like a big turnover, then baked."],
    ["caprese", "Caprese salad", "🍅🧀🌿🫒", "Slices of tomato and mozzarella with basil and olive oil, named after an island in the Bay of Naples.", ["caprese", "insalata caprese"]],
    ["vongole", "Spaghetti alle vongole", "🍝🐚🧄🍷", "Pasta tossed with clams, garlic, white wine and parsley.", ["vongole", "spaghetti vongole", "spaghetti with clams", "linguine alle vongole", "pasta alle vongole"]],
    ["arrabbiata", "Penne arrabbiata", "🍝🌶️🍅", "Quill-shaped pasta in an 'angry', fiery tomato and chilli sauce.", ["arrabbiata", "penne all'arrabbiata", "arrabiata", "penne arrabiata"]],
    ["cacio-e-pepe", "Cacio e pepe", "🍝🧀🧂", "Roman pasta made with just pecorino cheese, pasta water and lots of black pepper.", ["cacio pepe", "cacio e pepe pasta"]],
    ["saltimbocca", "Saltimbocca", "🥩🐖🌿", "Veal escalopes topped with prosciutto and sage - it 'jumps in the mouth'.", ["saltimbocca alla romana"]],
    ["parmigiana", "Parmigiana", "🍆🍅🧀", "Baked layers of fried aubergine, tomato sauce and cheese.", ["eggplant parmesan", "eggplant parmigiana", "melanzane alla parmigiana", "parmigiana di melanzane", "aubergine parmigiana"]],
    ["polenta", "Polenta", "🌽🧀🍄", "Cornmeal cooked into a thick golden porridge, served soft or set and grilled."],
    ["prosciutto-melone", "Prosciutto e melone", "🍈🥓", "Sweet ripe melon wrapped in thin slices of cured ham.", ["prosciutto and melon", "melon and prosciutto", "prosciutto melone", "melon and ham"]],
    ["carpaccio", "Carpaccio", "🥩🍋🧀", "Wafer-thin slices of raw beef with olive oil, lemon and parmesan shavings.", ["beef carpaccio"]],
    ["vitello-tonnato", "Vitello tonnato", "🐄🐟🍋", "Cold sliced veal under a creamy tuna and caper sauce, from Piedmont."],
    ["panettone", "Panettone", "🍞🍊🎄", "Tall, domed Milanese Christmas bread studded with candied fruit.", ["pannetone"]],
    ["affogato", "Affogato", "☕🍨", "A scoop of vanilla ice cream 'drowned' in a shot of hot espresso."],
    ["zabaglione", "Zabaglione", "🥚🍷🍮", "Egg yolks, sugar and Marsala whisked over heat into a warm, light foam.", ["zabaione", "sabayon"]],
    ["biscotti", "Biscotti", "☕🍪", "Twice-baked almond biscuits for dunking.", ["cantucci", "biscotto"]],
    ["ribollita", "Ribollita", "🍞🥬🥣", "Hearty Tuscan bread, bean and cabbage soup, 're-boiled' the next day."],
    ["tortellini", "Tortellini", "🥟🍲", "Little ring-shaped stuffed pasta, classically served floating in broth.", ["tortellini in brodo"]],
    ["pasta-e-fagioli", "Pasta e fagioli", "🥣🍝🍅", "Thick peasant soup of small pasta and beans.", ["pasta fagioli", "pasta fazool", "pasta e fasoi"]],
    ["frittata", "Frittata", "🍳🧀🥔", "Open-faced Italian omelette, finished in the oven and cut into wedges."],
    ["aglio-olio", "Spaghetti aglio e olio", "🍝🧄🫒🌶️", "The midnight pasta: just garlic, olive oil and chilli.", ["aglio e olio", "aglio olio", "spaghetti aglio olio"]],
    ["fiorentina", "Bistecca alla fiorentina", "🥩🔥🍷", "A huge T-bone steak grilled over coals and served rare, Florence-style.", ["florentine steak", "bistecca fiorentina", "fiorentina"]],
    ["norma", "Pasta alla Norma", "🍝🍆🍅🧀", "Sicilian pasta with fried aubergine, tomato and salted ricotta, named after an opera.", ["pasta norma", "norma"]],
    ["cannelloni", "Cannelloni", "🌯🧀🍅", "Large pasta tubes stuffed with ricotta or meat and baked in sauce.", ["canneloni"]],
    ["amatriciana", "Amatriciana", "🍝🥓🍅🌶️", "Tomato, cured pork cheek and pecorino sauce from a hill town near Rome.", ["pasta amatriciana", "all'amatriciana", "bucatini all'amatriciana", "spaghetti amatriciana", "matriciana"]],
    ["piadina", "Piadina", "🫓🧀🥓", "Thin flatbread from Romagna, folded around ham, cheese and rocket.", ["piada"]],
    ["granita", "Granita", "🧊🍋☕", "Sicilian crushed-ice dessert, often lemon or coffee, eaten with brioche."],
    ["cassata", "Cassata", "🎂🍒🧀", "Sicilian sponge cake with sweet ricotta, marzipan and candied fruit.", ["cassata siciliana"]],
    ["porchetta", "Porchetta", "🐖🌿🔥", "Rolled, herb-stuffed roast pork with crackling skin, sliced into sandwiches."],
    ["fritto-misto", "Fritto misto", "🦑🦐🍋", "A mixed platter of lightly battered, deep-fried seafood.", ["fritto misto di mare"]],
    ["puttanesca", "Puttanesca", "🍝🫒🐟🍅", "Punchy tomato sauce with olives, capers and anchovies.", ["spaghetti puttanesca", "pasta puttanesca", "alla puttanesca"]],
    ["panzanella", "Panzanella", "🍞🍅🥒", "Tuscan salad of stale bread soaked in ripe tomato juices, with cucumber and onion."],
    ["cotoletta", "Cotoletta alla milanese", "🥩🍞🍋", "Bone-in veal chop, breaded and pan-fried in butter, from Milan.", ["cotoletta", "veal milanese", "milanese", "cotoletta milanese"]],
  ],

  Asian: [
    ["sushi", "Sushi", "🍣🍚🐟", "Japanese vinegared rice topped or rolled with raw fish.", ["sushi roll", "maki", "nigiri"]],
    ["ramen", "Ramen", "🍜🥚🐖", "Japanese wheat-noodle soup with rich broth, sliced pork and a soft-boiled egg.", ["ramen noodles"]],
    ["pad-thai", "Pad Thai", "🍜🥜🦐🍋", "Stir-fried rice noodles with peanuts, shrimp and lime - Bangkok street-food royalty."],
    ["pho", "Pho", "🍜🐄🌿🌶️", "Vietnamese beef broth with rice noodles and a pile of fresh herbs.", ["phở", "pho bo"]],
    ["dumplings", "Dumplings", "🥟🥢", "Pleated little dough parcels with a savoury filling, steamed or pan-fried.", ["dumpling", "gyoza", "jiaozi", "potstickers", "dim sum"]],
    ["fried-rice", "Fried rice", "🍳🍚🥕🧅", "Yesterday's rice tossed in a very hot wok with egg and vegetables.", ["egg fried rice"]],
    ["butter-chicken", "Butter chicken", "🍗🧈🍅🍛", "A mild, creamy tomato curry that first came out of a Delhi restaurant.", ["murgh makhani", "chicken makhani"]],
    ["biryani", "Biryani", "🍚🍗🌶️🧅", "Fragrant rice layered with spiced meat and slow-cooked in a sealed pot.", ["biriyani", "chicken biryani", "briyani"]],
    ["bibimbap", "Bibimbap", "🍚🥚🥕🌶️🥢", "Korean rice bowl topped with vegetables, a fried egg and red chilli paste - stir it all up."],
    ["peking-duck", "Peking duck", "🦆🥞🥒", "Crispy-skinned roast duck rolled up in thin pancakes with cucumber and hoisin.", ["beijing duck"]],
    ["samosa", "Samosa", "🔺🥔🌶️", "Crisp triangular pastry stuffed with spiced potato and peas.", ["samosas"]],
    ["tempura", "Tempura", "🍤🥕🥢", "Japanese seafood and vegetables in an ultra-light, crackly batter."],
    ["teriyaki", "Teriyaki chicken", "🍗🍯🥢", "Chicken glazed in a sweet, shiny soy and mirin sauce, Japanese style.", ["teriyaki", "chicken teriyaki"]],
    ["udon", "Udon", "🍜🍥🧅", "Thick, chewy Japanese wheat noodles in a light dashi broth.", ["udon noodles"]],
    ["miso-soup", "Miso soup", "🥣🥢🌊", "Japanese soup of fermented soybean paste with cubes of tofu and seaweed.", ["miso"]],
    ["katsu-curry", "Katsu curry", "🐖🍛🍚", "A breaded, fried cutlet with mild Japanese curry sauce over rice.", ["katsu", "chicken katsu curry", "katsu kare", "tonkatsu curry"]],
    ["okonomiyaki", "Okonomiyaki", "🥞🥬🐙", "Savoury Osaka pancake of cabbage and batter, topped with mayo and bonito flakes - 'grilled as you like it'."],
    ["takoyaki", "Takoyaki", "🐙⚪🥢", "Ball-shaped batter snacks with a piece of octopus inside, an Osaka street favourite."],
    ["onigiri", "Onigiri", "🍙🐟", "Japanese triangle of rice wrapped in a strip of seaweed, often with a filling.", ["rice ball", "rice balls"]],
    ["mochi", "Mochi", "⚪🍚🍵", "Soft, chewy pounded sticky-rice cakes, sometimes wrapped around ice cream.", ["daifuku"]],
    ["yakitori", "Yakitori", "🍢🐔🔥", "Japanese skewers of grilled chicken brushed with sweet soy glaze."],
    ["sashimi", "Sashimi", "🐟🔪🥢", "Slices of very fresh raw fish served on their own, without rice."],
    ["kung-pao", "Kung Pao chicken", "🐔🥜🌶️", "Sichuan stir-fry of chicken, peanuts and dried chillies.", ["kung po chicken", "gong bao chicken", "kung pao", "kungpao chicken"]],
    ["sweet-sour-pork", "Sweet and sour pork", "🐖🍍🫑", "Battered pork in a glossy, tangy pineapple and pepper sauce.", ["sweet and sour", "sweet & sour pork", "sweet n sour pork"]],
    ["mapo-tofu", "Mapo tofu", "🌶️⬜🥩", "Sichuan tofu in a fiery, numbing sauce with minced pork.", ["mapo doufu"]],
    ["chow-mein", "Chow mein", "🍜🥕🥬", "Stir-fried egg noodles with vegetables and meat.", ["chowmein", "chow mien"]],
    ["hot-pot", "Hot pot", "🍲🌶️🥩🥬", "A simmering communal pot of broth where everyone cooks their own meat and veg at the table.", ["hotpot", "chinese hot pot"]],
    ["spring-rolls", "Spring rolls", "🌯🥬🥕", "Crispy fried rolls of thin pastry wrapped around shredded vegetables.", ["spring roll"]],
    ["char-siu", "Char siu", "🐖🍯🔥", "Cantonese barbecued pork with a sticky red glaze.", ["char siu pork", "cha siu", "chashao"]],
    ["bao", "Bao buns", "☁️🐖🥢", "Soft, cloud-like folded buns cooked in a steamer around fillings like braised pork belly.", ["bao", "gua bao", "steamed buns", "bao bun", "baozi"]],
    ["congee", "Congee", "🥣🍚🧅", "Rice simmered for hours into a soft, soupy breakfast across East Asia.", ["jook", "rice porridge", "juk", "zhou"]],
    ["bulgogi", "Bulgogi", "🥩🔥🥬", "Thin slices of marinated beef grilled at the table and wrapped in lettuce, Korean style.", ["bulgogi beef"]],
    ["japchae", "Japchae", "🍜🥕🍄", "Korean glass noodles stir-fried with vegetables and sesame oil.", ["chapchae", "jabchae"]],
    ["tteokbokki", "Tteokbokki", "🍡🌶️🔥", "Chewy Korean rice cakes in a sweet, spicy red sauce.", ["topokki", "ddeokbokki", "dukbokki"]],
    ["kimbap", "Kimbap", "🍙🥒🥕🥚", "Korean seaweed-wrapped rice rolls with vegetables, egg and ham.", ["gimbap"]],
    ["korean-fried-chicken", "Korean fried chicken", "🍗🌶️🍯", "Twice-fried, extra-crunchy chicken tossed in a sweet-spicy glaze.", ["yangnyeom chicken", "korean chicken"]],
    ["tandoori", "Tandoori chicken", "🍗🔥🌶️", "Chicken marinated in yogurt and spices, roasted in a clay oven until charred.", ["tandoori"]],
    ["tikka-masala", "Chicken tikka masala", "🍗🍅🍛🌶️", "Chargrilled chicken pieces in a spiced, creamy orange sauce - Britain's adopted favourite.", ["tikka masala"]],
    ["dal", "Dal", "🍲🌶️🍚", "Comforting spiced lentil stew, eaten daily across South Asia.", ["dhal", "daal", "dahl", "tarka dal", "dal tadka"]],
    ["naan", "Naan", "🫓🔥🧈", "Pillowy leavened flatbread slapped onto the wall of a tandoor oven.", ["nan", "naan bread", "garlic naan"]],
    ["palak-paneer", "Palak paneer", "🥬🧀🍛", "Mild cubes of fresh Indian cheese in a smooth spinach gravy.", ["saag paneer", "palak panir"]],
    ["dosa", "Masala dosa", "🫓🥔🥥", "Huge, paper-thin crispy South Indian crêpe wrapped around spiced potato.", ["dosa", "masala dosai", "dosai"]],
    ["chana-masala", "Chana masala", "🍛🧅🍅", "Punjabi curry of chickpeas in a tangy tomato and onion gravy.", ["chole", "chana", "channa masala"]],
    ["rogan-josh", "Rogan josh", "🍖🌶️🍛", "Rich, deep-red Kashmiri lamb curry.", ["lamb rogan josh", "roghan josh"]],
    ["laksa", "Laksa", "🍜🥥🌶️🦐", "Spicy coconut curry noodle soup from Malaysia and Singapore."],
    ["nasi-goreng", "Nasi goreng", "🍚🍳🌶️🦐", "Indonesia's sweet-soy fried rice, topped with a fried egg."],
    ["satay", "Satay", "🍢🥜🥒🍚", "Southeast Asian grilled meat skewers with a peanut dipping sauce.", ["sate", "chicken satay"]],
    ["rendang", "Rendang", "🥩🥥🌶️", "Indonesian beef slow-cooked in coconut milk and spices until almost dry.", ["beef rendang"]],
    ["tom-yum", "Tom yum", "🍲🦐🍋🌶️", "Hot and sour Thai soup with lemongrass, lime leaves and prawns.", ["tom yum goong", "tom yam", "tom yum soup"]],
    ["green-curry", "Green curry", "🟢🍛🥥", "Thai coconut curry made fragrant with green chillies and Thai basil.", ["thai green curry", "gaeng keow wan"]],
    ["som-tam", "Som tam", "🥗🌶️🥜🍋", "Shredded unripe papaya pounded in a mortar with chilli, lime and peanuts - sour, sweet and fiery.", ["papaya salad", "green papaya salad", "som tum"]],
    ["banh-mi", "Banh mi", "🥖🐖🥕🌿", "Vietnamese baguette sandwich with pâté, pork, pickled carrot and herbs.", ["bánh mì", "banh mi sandwich", "bahn mi"]],
    ["adobo", "Adobo", "🍗🧄🍶🍚", "The Philippines' chicken or pork braised in vinegar, soy and garlic.", ["chicken adobo", "pork adobo"]],
    ["chicken-rice", "Hainanese chicken rice", "🐔🍚🥒", "Poached chicken over rice cooked in its own stock - a Singapore icon.", ["chicken rice", "hainan chicken rice"]],
    ["massaman", "Massaman curry", "🥔🥜🍛🥥", "Mild, sweet-spiced Thai curry with potatoes and peanuts.", ["massaman", "matsaman curry", "mussaman curry"]],
  ],

  African: [
    ["jollof", "Jollof rice", "🍚🍅🌶️🔥", "Smoky, tomatoey party rice that West African countries love to argue over.", ["jollof"]],
    ["bunny-chow", "Bunny chow", "🍞🍛", "A hollowed-out loaf of bread filled with curry, from Durban in South Africa."],
    ["tagine", "Tagine", "🍲🥕🍋🫒", "Moroccan stew slow-cooked in a clay pot with a tall cone-shaped lid.", ["tajine", "chicken tagine"]],
    ["doro-wat", "Doro wat", "🍗🌶️🥚🫓", "Fiery Ethiopian chicken stew with hard-boiled eggs, scooped up with spongy flatbread.", ["doro wot", "doro wet"]],
    ["bobotie", "Bobotie", "🥩🥚🍛", "South African spiced mince baked under a golden egg custard."],
    ["shakshuka", "Shakshuka", "🍳🍅🌶️", "Eggs poached in a bubbling spiced tomato and pepper sauce, from North Africa.", ["shakshouka", "chakchouka"]],
    ["suya", "Suya", "🍢🥜🌶️", "Nigerian street-grilled meat skewers coated in a spicy peanut rub."],
    ["fufu", "Fufu", "🍠🥣", "Pounded, stretchy dough of cassava or yam, torn off by hand and dipped in soup.", ["foofoo", "foufou"]],
    ["couscous", "Couscous", "🥣🥕🍗🌶️", "North Africa's tiny steamed semolina grains under a vegetable and meat stew.", ["cous cous", "kuskus", "kesksou"]],
    ["egusi", "Egusi soup", "🍲🎃🥬", "West African soup thickened with ground melon seeds and full of leafy greens.", ["egusi"]],
    ["moin-moin", "Moin moin", "🍮🌶️🥚", "Nigerian steamed bean pudding with peppers, often with a piece of egg inside.", ["moi moi", "moyin moyin", "moinmoin"]],
    ["puff-puff", "Puff-puff", "🍩⚪🍬", "Sweet, fluffy deep-fried dough balls, a West African street snack.", ["puff puff", "bofrot"]],
    ["chin-chin", "Chin chin", "🍪🧈🟨", "Crunchy little fried cubes of sweet dough, a Nigerian party snack.", ["chinchin"]],
    ["kelewele", "Kelewele", "🍌🌶️🔥", "Ghanaian fried plantain cubes spiced with ginger and chilli.", ["kele wele"]],
    ["waakye", "Waakye", "🍚🍝🥚🌶️", "Ghanaian rice and beans cooked with sorghum leaves, served with spaghetti, egg and black pepper sauce.", ["waakye rice"]],
    ["banku", "Banku", "🌽⚪🐟", "Ghanaian fermented corn and cassava dough, served with grilled tilapia and pepper sauce."],
    ["pepper-soup", "Pepper soup", "🍲🌶️🐟", "Light, fiery West African broth with meat or fish and warming spices.", ["nigerian pepper soup", "peppersoup"]],
    ["thieboudienne", "Thieboudienne", "🐟🍚🥕", "Senegal's national dish: fish and vegetables simmered with broken rice in tomato.", ["ceebu jen", "thiebou dienne", "thieboudiene", "thieboudienne", "ceebu jenn"]],
    ["yassa", "Yassa", "🍗🧅🍋", "Senegalese chicken marinated and braised with heaps of onion and lemon.", ["chicken yassa", "poulet yassa"]],
    ["mafe", "Mafé", "🥜🍲🥩", "West African meat stew in a rich peanut sauce.", ["mafe", "maafe", "groundnut stew", "peanut stew", "domoda"]],
    ["akara", "Akara", "🟠🔥🍞", "Deep-fried black-eyed pea fritters, a breakfast favourite in Nigeria.", ["accara", "bean cakes", "akara balls"]],
    ["ugali", "Ugali", "🌽⚪🥬", "Stiff maize-flour porridge eaten by hand across East Africa.", ["posho", "nsima", "sadza", "pap", "nshima"]],
    ["nyama-choma", "Nyama choma", "🥩🔥🍺", "Kenya's 'grilled meat': goat or beef roasted slowly over coals.", ["nyama-choma"]],
    ["sukuma-wiki", "Sukuma wiki", "🥬🧅🍅", "Kenyan braised collard greens with onion and tomato - it 'stretches the week'."],
    ["pilau", "Pilau", "🍚🍖🌿", "Spiced rice from the Swahili coast with cumin, cardamom and meat.", ["pilau rice", "pilawo"]],
    ["mandazi", "Mandazi", "🍩🥥☕", "East African fried dough triangles flavoured with coconut and cardamom.", ["mandaazi", "maandazi"]],
    ["chapati", "Chapati", "🫓🌀🧈", "Soft, layered unleavened flatbread, an everyday staple across East Africa.", ["chapatti", "chapo"]],
    ["rolex", "Rolex", "🍳🫓🌯", "Uganda's street snack: an omelette rolled up inside a chapati.", ["rolled eggs"]],
    ["matoke", "Matoke", "🍌🍲", "Ugandan green bananas steamed and mashed, often cooked in their own leaves.", ["matooke"]],
    ["kitfo", "Kitfo", "🥩🌶️🧈", "Ethiopian minced raw beef warmed in spiced clarified butter and chilli powder."],
    ["shiro", "Shiro", "🍲🌶️🫓", "Ethiopian chickpea-flour stew, smooth and spiced, scooped up with flatbread.", ["shiro wat", "shiro wot"]],
    ["biltong", "Biltong", "🥩🧂🌬️", "South African air-dried, spiced strips of cured meat."],
    ["boerewors", "Boerewors", "🌭🌀🔥", "South African coiled farmer's sausage, grilled on the braai.", ["boerie", "wors"]],
    ["chakalaka", "Chakalaka", "🥫🌶️🥕", "Spicy South African relish of beans, peppers and carrots."],
    ["malva-pudding", "Malva pudding", "🍮🍑🍦", "Spongy, sticky caramelised South African dessert made with apricot jam.", ["malva"]],
    ["koeksisters", "Koeksisters", "🥨🍯", "Plaited South African doughnuts plunged into ice-cold syrup.", ["koeksister", "koesister", "koesisters"]],
    ["vetkoek", "Vetkoek", "🥯🥩🌶️", "South African deep-fried dough bread, split and filled with curried mince.", ["vet koek"]],
    ["peri-peri", "Peri-peri chicken", "🍗🌶️🔥🍋", "Chicken basted in fiery bird's-eye chilli sauce, a Mozambican-Portuguese classic.", ["piri piri chicken", "peri peri chicken", "piri-piri chicken", "peri peri", "piri piri"]],
    ["harira", "Harira", "🍲🍋🍅", "Moroccan tomato, lentil and chickpea soup, eaten to break the Ramadan fast."],
    ["pastilla", "Pastilla", "🥧🐔🍬", "Moroccan flaky pie of shredded pigeon or chicken, dusted with sugar and cinnamon.", ["bastilla", "b'stilla", "bisteeya", "bastila"]],
    ["koshari", "Koshari", "🍝🍚🧅🍅", "Egypt's street-food heap of rice, lentils, pasta and crispy onions under tomato sauce.", ["kushari", "koshary"]],
    ["ful-medames", "Ful medames", "🥣🧄🍋🫓", "Slow-stewed fava beans with cumin, lemon and olive oil - an Egyptian breakfast.", ["ful", "foul medames", "ful mudammas", "foul"]],
    ["molokhia", "Molokhia", "🥬🍲🍚", "Silky green soup of finely chopped jute mallow leaves, loved in Egypt.", ["mulukhiyah", "molokhiya", "mloukhiya", "molokheya"]],
    ["brik", "Brik", "🔺🥚🐟", "Tunisian crisp fried pastry triangle with a runny egg inside.", ["brick", "brik a l'oeuf"]],
    ["merguez", "Merguez", "🌭🌶️🐑", "Spicy North African lamb sausage, red with harissa.", ["merguez sausage"]],
    ["sosaties", "Sosaties", "🍢🍑🔥", "South African curried lamb kebabs threaded with dried apricots.", ["sosatie"]],
    ["kachumbari", "Kachumbari", "🍅🧅🌶️🥗", "East African fresh tomato and onion salad with chilli and lime."],
    ["ndole", "Ndolé", "🥬🥜🦐", "Cameroon's national dish: bitterleaf stewed with peanuts and shrimp.", ["ndole"]],
    ["attieke", "Attiéké", "🐟⚪🌶️", "Ivorian fermented cassava 'couscous', served with grilled fish.", ["attieke", "acheke"]],
    ["efo-riro", "Efo riro", "🥬🌶️🐟", "Yoruba stew of spinach-like greens cooked in a rich pepper base.", ["efo"]],
    ["okra-soup", "Okra soup", "🍲🦐🌿", "Slippery 'draw' soup thickened with chopped okra, enjoyed across West Africa.", ["okro soup", "okra stew", "okro"]],
  ],

  "Latin American": [
    ["tacos", "Tacos", "🌮🥩🧅🌿", "Small folded corn tortillas with fillings like grilled meat, onion and coriander.", ["taco"]],
    ["burrito", "Burrito", "🌯🍚🧀🥑", "A big flour tortilla wrapped tight around rice, beans, meat and cheese."],
    ["guacamole", "Guacamole", "🥑🍋🧅🌶️", "Mashed avocado dip with lime, onion and chilli.", ["guac"]],
    ["ceviche", "Ceviche", "🐟🍋🧅🌶️", "Raw fish \"cooked\" in lime juice - Peru's national dish.", ["cebiche", "seviche"]],
    ["empanadas", "Empanadas", "🥧🥩🫒", "Half-moon pastries filled with meat, baked or fried all over Latin America.", ["empanada"]],
    ["feijoada", "Feijoada", "🍲🐖🍚", "Brazil's slow-cooked black bean and pork stew, served with rice and orange slices."],
    ["arepas", "Arepas", "🫓🧀🥑", "Venezuelan and Colombian corn cakes, split open and stuffed.", ["arepa"]],
    ["churros", "Churros", "🍩🍫☕", "Ridged sticks of fried dough rolled in cinnamon sugar and dunked in chocolate.", ["churro"]],
    ["quesadilla", "Quesadilla", "🧀🫓🔥", "A tortilla folded around melted cheese and toasted on a griddle.", ["quesadillas"]],
    ["enchiladas", "Enchiladas", "🌯🌶️🧀🍅", "Rolled corn tortillas, filled and baked under chilli sauce and cheese.", ["enchilada"]],
    ["nachos", "Nachos", "🔺🧀🌶️🥑", "Tortilla chips piled high with melted cheese, jalapeños and toppings.", ["nacho"]],
    ["tamales", "Tamales", "🌽🍃🥩", "Corn masa dough with a filling, wrapped in a corn husk and steamed.", ["tamale", "tamal"]],
    ["pozole", "Pozole", "🥣🌽🐖", "Mexican hominy and pork stew, garnished with radish, cabbage and lime.", ["posole"]],
    ["mole", "Mole poblano", "🍗🍫🌶️", "Dark, rich sauce of chillies, spices and chocolate, poured over turkey or chicken.", ["mole"]],
    ["elote", "Elote", "🌽🧀🌶️🍋", "Grilled corn on the cob slathered in mayo, crumbly cheese and chilli.", ["mexican street corn", "elotes", "street corn"]],
    ["chilaquiles", "Chilaquiles", "🔺🍳🌶️", "Fried tortilla pieces simmered in salsa and topped with egg - a Mexican breakfast."],
    ["huevos-rancheros", "Huevos rancheros", "🍳🌶️🫓", "Fried eggs on tortillas smothered in a tomato-chilli salsa.", ["huevos ranchero", "ranchero eggs"]],
    ["carnitas", "Carnitas", "🐖🍊🔥", "Pork slow-cooked in its own fat until meltingly tender with crispy edges."],
    ["flan", "Flan", "🍮🍯", "Silky caramel-topped custard, a favourite across Latin America.", ["flan de leche", "caramel flan", "creme caramel"]],
    ["tres-leches", "Tres leches cake", "🍰🥛🥛🥛", "Sponge cake soaked in three kinds of milk.", ["tres leches", "pastel de tres leches"]],
    ["dulce-de-leche", "Dulce de leche", "🥛🍯", "Sweetened milk cooked slowly into a thick caramel spread.", ["dulce de leche", "cajeta"]],
    ["alfajores", "Alfajores", "🍪🍯🥥", "Two crumbly biscuits sandwiched with milk caramel, edges rolled in coconut.", ["alfajor"]],
    ["brigadeiros", "Brigadeiros", "🍫🟤🎉", "Brazilian chocolate fudge balls rolled in sprinkles, a must at birthday parties.", ["brigadeiro"]],
    ["pao-de-queijo", "Pão de queijo", "🧀🍞⚪", "Chewy little Brazilian rolls with cheese baked into the dough, made with cassava flour.", ["pao de queijo", "brazilian cheese bread", "cheese bread"]],
    ["coxinha", "Coxinha", "🐔💧🔥", "Brazilian teardrop-shaped fried croquette filled with shredded chicken.", ["coxinhas"]],
    ["picanha", "Picanha", "🥩🔥🧂", "Brazil's prized cut of beef rump cap, skewered and grilled with coarse salt."],
    ["moqueca", "Moqueca", "🐟🥥🌶️🍅", "Brazilian fish stew with coconut milk, peppers and palm oil.", ["moqueca baiana"]],
    ["acai", "Açaí bowl", "🫐🍌🥣", "Frozen purple berry purée topped with granola and banana.", ["acai bowl", "acai"]],
    ["lomo-saltado", "Lomo saltado", "🥩🍟🍅🍚", "Peruvian stir-fry of beef, tomato and onion served with fries and rice."],
    ["causa", "Causa", "🥔🍋🥑", "Peruvian layered cold terrine of lime-spiked yellow potato with chicken or tuna.", ["causa limena", "causa rellena"]],
    ["pollo-a-la-brasa", "Pollo a la brasa", "🐔🔥🍟", "Peruvian rotisserie chicken in a spiced marinade, served with fries.", ["peruvian chicken", "peruvian roast chicken"]],
    ["anticuchos", "Anticuchos", "🍢❤️🔥", "Peruvian grilled skewers of marinated beef heart.", ["anticucho"]],
    ["asado", "Asado", "🥩🌭🔥🍷", "Argentina's grand barbecue of beef cuts and sausages slow-grilled over wood embers."],
    ["chimichurri", "Chimichurri", "🌿🧄🫒", "Argentine sauce of parsley, garlic, vinegar and oregano for grilled meat."],
    ["choripan", "Choripán", "🌭🍞🌿", "Argentine grilled chorizo sausage in crusty bread with a green herb sauce.", ["choripan"]],
    ["pupusas", "Pupusas", "🫓🧀🥬", "Salvadoran thick corn tortillas stuffed with cheese, beans or pork, served with pickled cabbage.", ["pupusa"]],
    ["gallo-pinto", "Gallo pinto", "🍚🐓🍳", "Costa Rican and Nicaraguan breakfast of rice and beans fried together.", ["gallopinto"]],
    ["ropa-vieja", "Ropa vieja", "🥩👕🍅", "Cuban shredded beef stewed in tomato - its name means 'old clothes'."],
    ["cuban-sandwich", "Cuban sandwich", "🥪🐖🧀🥒", "Pressed sandwich of roast pork, ham, Swiss cheese, pickles and mustard.", ["cubano", "cuban"]],
    ["mofongo", "Mofongo", "🍌🧄🐖", "Puerto Rican mashed fried green plantains with garlic and pork crackling."],
    ["arroz-con-pollo", "Arroz con pollo", "🍚🐔🫑", "Latin American one-pot rice with chicken, peppers and saffron or annatto.", ["chicken and rice"]],
    ["sancocho", "Sancocho", "🍲🌽🍠", "Hearty Caribbean and Latin American meat and root-vegetable stew."],
    ["bandeja-paisa", "Bandeja paisa", "🍳🥩🍚🥑", "Colombia's huge platter of beans, rice, meat, crackling, fried egg and avocado."],
    ["chicharron", "Chicharrón", "🐖🔥🧂", "Crunchy fried pork belly or pork rinds.", ["chicharron", "chicharrones"]],
    ["tostones", "Tostones", "🍌🔨🧂", "Twice-fried, smashed green plantain slices.", ["patacones", "tostone"]],
    ["chiles-rellenos", "Chiles rellenos", "🫑🧀🍳", "Roasted poblano peppers stuffed with cheese, dipped in egg batter and fried.", ["chile relleno", "chili relleno", "chiles relleno", "chile rellenos"]],
    ["birria", "Birria", "🥩🌶️🍲🌮", "Jalisco's slow-braised spiced goat or beef, now famous as tacos dunked in their own broth.", ["birria tacos", "quesabirria"]],
    ["arroz-con-leche", "Arroz con leche", "🍚🥛🍬", "Rice slowly simmered in sweet milk with cinnamon, loved across Latin America.", ["rice pudding"]],
    ["pastel-de-choclo", "Pastel de choclo", "🌽🥩🥧", "Chilean bake of spiced minced beef under a sweet corn crust."],
    ["ajiaco", "Ajiaco", "🍲🥔🌽🐔", "Bogotá's chicken soup with three kinds of potato, corn and a herb called guascas."],
  ],

  "North American": [
    ["cheeseburger", "Cheeseburger", "🍔🧀🥬🍅", "A grilled beef patty with melted cheese, lettuce and tomato in a bun.", ["burger", "hamburger", "cheese burger"]],
    ["hot-dog", "Hot dog", "🌭🧅", "A sausage in a soft long bun - a baseball-stadium favourite.", ["hotdog", "frankfurter"]],
    ["mac-cheese", "Mac and cheese", "🧀🧀🥣🔥", "Elbow pasta baked in a gooey cheese sauce.", ["macaroni and cheese", "mac n cheese", "macaroni cheese", "mac & cheese"]],
    ["pancakes", "Pancakes", "🥞🧈🍯", "A fluffy breakfast stack with butter and maple syrup.", ["pancake", "hotcakes"]],
    ["apple-pie", "Apple pie", "🍎🥧", "Cinnamon-spiced fruit under a golden lattice crust - \"as American as\" it."],
    ["fried-chicken", "Fried chicken", "🍗🧂🔥", "Buttermilk-soaked chicken pieces in a crunchy seasoned coating, deep-fried.", ["southern fried chicken"]],
    ["clam-chowder", "Clam chowder", "🐚🥔🥣", "Creamy New England soup with shellfish and potatoes.", ["chowder", "new england clam chowder"]],
    ["poutine", "Poutine", "🍟🧀🍖", "Canadian fries smothered in cheese curds and gravy."],
    ["fajitas", "Fajitas", "🥩🫑🧅🔥", "Sizzling Tex-Mex strips of grilled steak or chicken with peppers and onions, wrapped at the table.", ["fajita"]],
    ["bbq-ribs", "Barbecue ribs", "🍖🔥🍯", "Slow-smoked racks of pork, glazed in a sticky, tangy sauce.", ["bbq ribs", "ribs", "spare ribs", "baby back ribs", "barbeque ribs"]],
    ["pulled-pork", "Pulled pork", "🐖🔥🍞", "Smoked pork shoulder shredded and piled into a soft bun with slaw.", ["pulled pork sandwich"]],
    ["buffalo-wings", "Buffalo wings", "🍗🌶️🧈🧀", "Deep-fried chicken flats and drumettes tossed in hot sauce and butter, with blue cheese dip.", ["chicken wings", "hot wings", "wings", "buffalo chicken wings"]],
    ["cheesesteak", "Philly cheesesteak", "🥖🥩🧀🧅", "Thin-sliced griddled beef and melted cheese in a long roll, from Philadelphia.", ["cheesesteak", "philly cheese steak", "cheese steak", "philadelphia cheesesteak"]],
    ["lobster-roll", "Lobster roll", "🦞🥖🧈", "Chunks of lobster in butter or mayo stuffed in a toasted split-top bun.", ["lobster rolls"]],
    ["gumbo", "Gumbo", "🍲🦐🌶️🍚", "Thick Louisiana stew of seafood and sausage built on a dark roux, served over rice."],
    ["jambalaya", "Jambalaya", "🍚🦐🌭🌶️", "Cajun and Creole one-pot rice with sausage, chicken and shrimp."],
    ["biscuits-gravy", "Biscuits and gravy", "🍞🌭🥛", "Southern breakfast of fluffy scone-like bread smothered in creamy sausage gravy.", ["biscuits & gravy", "biscuits n gravy"]],
    ["cornbread", "Cornbread", "🌽🍞🧈", "Crumbly, slightly sweet skillet bread made from cornmeal.", ["corn bread"]],
    ["meatloaf", "Meatloaf", "🥩🍞🍅", "Ground meat shaped into a loaf, glazed with ketchup and baked.", ["meat loaf"]],
    ["pot-roast", "Pot roast", "🥩🥕🥔🍲", "Beef slowly braised in a covered pot with carrots and potatoes for Sunday dinner."],
    ["chili", "Chili con carne", "🌶️🥩🍲", "Spicy Texan stew of beef and chillies, often with beans.", ["chili", "chilli", "chilli con carne", "texas chili"]],
    ["corn-dog", "Corn dog", "🌭🌽🔥", "A sausage dipped in cornmeal batter and deep-fried on a stick.", ["corndog"]],
    ["sloppy-joe", "Sloppy joe", "🍔🥩🍅", "Loose, saucy ground beef in a bun - messy by name and by nature.", ["sloppy joes"]],
    ["reuben", "Reuben sandwich", "🥪🥩🥬🧀", "Corned beef, Swiss cheese and sauerkraut on toasted rye.", ["reuben"]],
    ["blt", "BLT", "🥓🥬🍅🍞", "A three-letter sandwich of crispy cured pork, crunchy leaves and juicy red slices.", ["blt sandwich", "bacon lettuce and tomato", "bacon lettuce tomato"]],
    ["bagel-lox", "Bagel and lox", "🥯🐟🧀", "New York breakfast: a chewy ring of bread with smoked salmon and cream cheese.", ["bagel with lox", "lox and bagel", "bagels and lox", "bagel lox", "lox bagel"]],
    ["cheesecake", "Cheesecake", "🍰🧀🍓", "Dense, rich cream-cheese dessert on a graham-cracker crust, New York style.", ["new york cheesecake"]],
    ["brownies", "Brownies", "🍫🟫🥛", "Fudgy chocolate squares baked in a tray.", ["brownie", "chocolate brownies"]],
    ["choc-chip-cookies", "Chocolate chip cookies", "🍪🍫🥛", "Chewy, buttery biscuits studded with chocolate pieces.", ["chocolate chip cookie", "cookies", "choc chip cookies", "cookie"]],
    ["pumpkin-pie", "Pumpkin pie", "🎃🥧", "Spiced squash custard tart, a Thanksgiving tradition."],
    ["pecan-pie", "Pecan pie", "🥜🥧🍯", "Southern pie of nuts set in a gooey, syrupy filling."],
    ["key-lime-pie", "Key lime pie", "🍋🥧🌴", "Tart Florida custard pie made from small citrus fruits and condensed milk.", ["key lime"]],
    ["smores", "S'mores", "🔥🍫🍪", "Campfire treat: toasted marshmallow and chocolate squashed between crackers.", ["smores", "smore", "s'more"]],
    ["doughnuts", "Doughnuts", "🍩🍩", "Fried rings of sweet dough, glazed or covered in sprinkles.", ["donuts", "doughnut", "donut"]],
    ["waffles", "Waffles", "🧇🍓🍯", "Grid-patterned batter cakes with deep pockets for syrup.", ["waffle"]],
    ["eggs-benedict", "Eggs Benedict", "🍳🥯🥓🧈", "Toasted muffins topped with ham, poached eggs and hollandaise.", ["eggs benny", "egg benedict"]],
    ["hash-browns", "Hash browns", "🥔🍳🟫", "Shredded potatoes fried into a crisp golden patty.", ["hashbrowns", "hash brown"]],
    ["grilled-cheese", "Grilled cheese", "🧀🍞🔥", "Buttered bread toasted in a pan around melted cheese.", ["grilled cheese sandwich"]],
    ["cobb-salad", "Cobb salad", "🥗🥓🥚🥑", "Chopped salad of chicken, bacon, egg, avocado and blue cheese, from Hollywood.", ["cobb"]],
    ["caesar-salad", "Caesar salad", "🥗🧀🍞", "Romaine lettuce with croutons, parmesan and a garlicky anchovy dressing - born in Tijuana.", ["caesar"]],
    ["nanaimo-bars", "Nanaimo bars", "🍫🥥🟨", "Canadian no-bake layered bar of crumb base, custard icing and chocolate.", ["nanaimo bar"]],
    ["butter-tarts", "Butter tarts", "🧈🥧🍁", "Little Canadian pastries filled with a sweet, runny syrup filling.", ["butter tart"]],
    ["tourtiere", "Tourtière", "🥧🥩🍁", "Québécois spiced meat pie, a Christmas Eve favourite.", ["tourtiere"]],
    ["pbj", "PB&J", "🥜🍇🍞", "Lunchbox classic of nut spread and grape jam between two slices of bread.", ["pb and j", "pbj", "peanut butter and jelly", "peanut butter and jelly sandwich", "peanut butter jelly sandwich"]],
    ["shrimp-grits", "Shrimp and grits", "🦐🌽🧈", "Lowcountry dish of shrimp over creamy ground-corn porridge.", ["shrimp & grits"]],
    ["crab-cakes", "Crab cakes", "🦀🍋🍞", "Maryland's pan-fried patties of lump crab meat.", ["crab cake", "maryland crab cakes"]],
    ["cinnamon-rolls", "Cinnamon rolls", "🌀🥐🍯", "Soft spiral buns swirled with cinnamon sugar and topped with icing.", ["cinnamon roll", "cinnamon buns", "cinnamon bun"]],
    ["banana-split", "Banana split", "🍌🍨🍒", "A halved banana in a long dish with three scoops of ice cream and toppings."],
    ["fried-green-tomatoes", "Fried green tomatoes", "🍅🟢🍳", "Southern slices of unripe tomato coated in cornmeal and fried.", ["fried green tomato"]],
    ["chicken-waffles", "Chicken and waffles", "🍗🧇🍯", "Soul-food pairing of crispy fried chicken on syrup-drizzled waffles.", ["chicken & waffles", "chicken n waffles"]],
  ],

  European: [
    ["fish-chips", "Fish and chips", "🐟🍟🍋", "Britain's favourite takeaway: battered white fish with thick-cut fries.", ["fish n chips", "fish & chips", "fish chips"]],
    ["croissant", "Croissant", "🥐☕", "A flaky, buttery, crescent-shaped French pastry.", ["croissants"]],
    ["paella", "Paella", "🥘🦐🍚🍋", "Saffron rice cooked in a wide shallow pan with seafood or chicken, from Valencia."],
    ["fondue", "Fondue", "🫕🧀🍞", "A communal Swiss pot of melted cheese for dipping bread.", ["cheese fondue"]],
    ["moussaka", "Moussaka", "🍆🥩🧀", "Greek bake of layered aubergine, spiced meat and béchamel.", ["musaka"]],
    ["creme-brulee", "Crème brûlée", "🍮🔥🥄", "Rich vanilla custard under a thin layer of sugar caramelised with a torch.", ["creme brulee", "burnt cream"]],
    ["goulash", "Goulash", "🥘🌶️🥩", "Hungarian beef stew, deep red with paprika.", ["gulyas", "gulasch"]],
    ["full-english", "Full English breakfast", "🍳🥓🌭🍄", "The big British cooked breakfast: eggs, bacon, sausage, beans, mushrooms and toast.", ["full english", "english breakfast", "fry up", "fry-up"]],
    ["shepherds-pie", "Shepherd's pie", "🥧🐑🥔", "Minced lamb in gravy under a crust of mashed potato.", ["shepherds pie", "cottage pie"]],
    ["bangers-mash", "Bangers and mash", "🌭🥔🧅", "British sausages on mashed potato with onion gravy.", ["bangers & mash", "sausage and mash", "bangers n mash"]],
    ["yorkshire-pudding", "Yorkshire pudding", "🥩💨🥣", "Puffed, crisp batter cups baked in sizzling fat, served with roast beef and gravy.", ["yorkshire puddings", "yorkie"]],
    ["beef-wellington", "Beef Wellington", "🥩🥐🍄", "Beef fillet coated in mushroom paste and wrapped in puff pastry.", ["wellington"]],
    ["scones", "Scones", "🫖🍓🧈", "British tea-time bakes split and topped with clotted cream and jam.", ["scone", "cream tea"]],
    ["haggis", "Haggis", "🐑🥔🥃", "Scotland's spiced sheep's offal and oats, served with neeps and tatties.", ["haggis neeps and tatties"]],
    ["irish-stew", "Irish stew", "🍲🐑🥔", "Slow-cooked lamb or mutton with potatoes, onions and carrots."],
    ["cornish-pasty", "Cornish pasty", "🥟🥩🥔", "Crimped D-shaped pastry of beef, potato and swede - a tin miner's lunch.", ["pasty", "cornish pasties"]],
    ["sticky-toffee", "Sticky toffee pudding", "🍮🍯🌴", "Moist date sponge drenched in hot caramel sauce.", ["sticky toffee"]],
    ["ratatouille", "Ratatouille", "🍆🍅🫑🧅", "Provençal stew of aubergine, courgette, peppers and tomato."],
    ["coq-au-vin", "Coq au vin", "🐓🍷🍄", "Chicken braised in red wine with mushrooms and bacon.", ["coq a vin"]],
    ["bouillabaisse", "Bouillabaisse", "🐟🦐🍲🍞", "Marseille's saffron fish stew, served with garlicky toast.", ["bouillabaise"]],
    ["quiche", "Quiche Lorraine", "🥧🥓🥚", "Open savoury tart of eggs, cream and bacon.", ["quiche"]],
    ["bourguignon", "Beef bourguignon", "🐄🍷🥕", "Burgundy beef stew slowly braised in red wine.", ["boeuf bourguignon", "beef burgundy", "bourguignon"]],
    ["crepes", "Crêpes", "🥞🍫🍓", "Paper-thin French pancakes, sweet or savoury.", ["crepe", "crepes"]],
    ["croque-monsieur", "Croque monsieur", "🥪🧀🔥", "French grilled ham-and-cheese sandwich topped with béchamel.", ["croque"]],
    ["escargots", "Escargots", "🐌🧈🧄", "Burgundy delicacy of garden molluscs baked in their shells with garlic and parsley butter.", ["escargot", "snails"]],
    ["macarons", "Macarons", "🍪🌈🎀", "Delicate almond-meringue sandwich biscuits in pastel colours.", ["macaron"]],
    ["french-onion-soup", "French onion soup", "🧅🥣🧀", "Slow-caramelised onions in beef broth under a cheesy bread crust.", ["onion soup", "soupe a l'oignon"]],
    ["tarte-tatin", "Tarte Tatin", "🍎🥧🔄", "Upside-down caramelised apple tart.", ["tatin"]],
    ["profiteroles", "Profiteroles", "🍫⚪🍦", "Cream-filled choux puffs drizzled with chocolate sauce.", ["profiterole"]],
    ["schnitzel", "Wiener schnitzel", "🥩🍋🥔", "Vienna's thin breaded veal cutlet, fried golden and served with lemon.", ["schnitzel", "weiner schnitzel"]],
    ["bratwurst", "Bratwurst", "🌭🍺🥨", "German grilled pork sausage with mustard and a crusty roll.", ["brat", "bratwurst sausage"]],
    ["pretzel", "Pretzel", "🥨🧂🍺", "Twisted, glossy brown baked dough sprinkled with coarse salt.", ["pretzels", "brezel"]],
    ["apple-strudel", "Apple strudel", "🍎🌀🍦", "Thin, flaky pastry rolled around spiced apple and raisins, from Vienna.", ["strudel", "apfelstrudel"]],
    ["black-forest", "Black Forest cake", "🍰🍒🍫", "German chocolate sponge layered with cherries, cream and kirsch.", ["black forest gateau", "schwarzwalder kirschtorte", "black forest"]],
    ["sachertorte", "Sachertorte", "🍫🍰🍑", "Viennese dense chocolate cake with a thin layer of apricot jam.", ["sacher torte", "sacher cake"]],
    ["currywurst", "Currywurst", "🌭🍛🍟", "Berlin street sausage sliced up and smothered in curried ketchup."],
    ["pierogi", "Pierogi", "🥟🥔🧅", "Polish half-moon dumplings filled with potato and cheese.", ["pierogies", "perogies", "pierogis", "perogi"]],
    ["borscht", "Borscht", "🥣🥕🥬💜", "Vibrant Eastern European beetroot soup, served with sour cream.", ["borsch", "borshch", "borsht"]],
    ["stroganoff", "Beef Stroganoff", "🥩🍄🥛", "Strips of beef in a mushroom and sour cream sauce.", ["stroganoff"]],
    ["chicken-kiev", "Chicken Kiev", "🐔🧈🧄", "Breaded chicken breast wrapped around a molten core of garlic butter.", ["chicken kyiv", "kiev", "kyiv"]],
    ["gazpacho", "Gazpacho", "🍅🥒🥣🧊", "Chilled Andalusian soup of blended tomato, cucumber and pepper."],
    ["spanish-omelette", "Spanish omelette", "🥔🥚🧅", "Thick, golden egg cake of slow-cooked potatoes and onions, served in wedges as tapas.", ["tortilla espanola", "spanish tortilla", "tortilla de patatas"]],
    ["patatas-bravas", "Patatas bravas", "🥔🌶️🍅", "Fried potato chunks with spicy tomato sauce and aioli - a classic tapa.", ["bravas"]],
    ["pastel-de-nata", "Pastel de nata", "🥧🍮☕", "Little Portuguese pastries of flaky crust filled with egg custard, blistered on top.", ["pasteis de nata", "portuguese custard tart", "custard tart", "pastel de belem"]],
    ["souvlaki", "Souvlaki", "🍢🐖🍋", "Greek grilled pork skewers, often wrapped in pitta with tzatziki.", ["souvlakia"]],
    ["spanakopita", "Spanakopita", "🥬🧀🥧", "Greek flaky filo pie of spinach and feta.", ["spinach pie"]],
    ["greek-salad", "Greek salad", "🍅🥒🫒🧀", "Chunky tomato, cucumber, onion and olives under a slab of feta.", ["horiatiki"]],
    ["swedish-meatballs", "Swedish meatballs", "⚪🥔🍒", "Small beef-and-pork balls in creamy gravy with lingonberry jam - IKEA's most famous dish.", ["kottbullar", "köttbullar", "meatballs"]],
    ["stroopwafels", "Stroopwafels", "🧇☕🍬", "Thin Dutch waffle cookies sandwiching a layer of caramel syrup, warmed over a hot drink.", ["stroopwafel"]],
    ["moules-frites", "Moules frites", "🦪🍟🍷", "Belgian pot of mussels steamed in wine, served with fries.", ["moules-frites", "mussels and fries", "mussels and chips"]],
    ["raclette", "Raclette", "🧀🥔🔥", "Swiss cheese melted and scraped over boiled potatoes and pickles."],
  ],

  "Middle Eastern": [
    ["falafel", "Falafel", "🧆🥙", "Deep-fried balls of ground chickpeas and herbs, tucked into pitta.", ["felafel", "falafels"]],
    ["shawarma", "Shawarma", "🥙🍗🔥", "Meat stacked on a slowly turning spit, shaved off and wrapped in flatbread.", ["shwarma", "chicken shawarma"]],
    ["hummus", "Hummus", "🧄🍋🥣", "Smooth dip of chickpeas, tahini, lemon and garlic.", ["houmous", "humus", "hommus"]],
    ["baba-ghanoush", "Baba ghanoush", "🍆🔥🥣", "Smoky roasted aubergine dip with tahini and lemon.", ["baba ganoush", "baba ghanouj", "baba ganouj", "mutabal"]],
    ["tabbouleh", "Tabbouleh", "🌿🍅🍋", "Lebanese salad of finely chopped parsley, bulgur, tomato and mint.", ["tabouleh", "tabouli", "tabbouli", "tabbouleh salad"]],
    ["fattoush", "Fattoush", "🥗🫓🍋", "Levantine salad tossed with crispy pieces of toasted pitta and sumac.", ["fattush"]],
    ["shish-kebab", "Shish kebab", "🍢🐑🔥", "Turkish cubes of marinated lamb threaded on a sword-like skewer and grilled.", ["shish kabob", "shish kebap", "sis kebab", "shish kabab"]],
    ["kofta", "Kofta", "🥩🧅🍢", "Spiced minced meat shaped around skewers and chargrilled.", ["kofte", "kafta", "kefta", "köfte", "kofta kebab"]],
    ["baklava", "Baklava", "🥜🍯🟨", "Layers of paper-thin filo, chopped nuts and sweet syrup.", ["baklawa"]],
    ["kunafa", "Kunafa", "🧀🍯🟠", "Shredded-pastry dessert with melted cheese inside, soaked in syrup.", ["knafeh", "kanafeh", "kunefe", "künefe", "knafe", "kunafeh"]],
    ["manakish", "Manakish", "🫓🌿🧀", "Lebanese flatbread topped with thyme-and-sesame spice mix and olive oil, a breakfast staple.", ["manakeesh", "manoushe", "man'oushe", "manaeesh", "manakeesh zaatar"]],
    ["mansaf", "Mansaf", "🐑🍚🥛", "Jordan's national dish of lamb cooked in fermented dried yogurt, over rice."],
    ["maqluba", "Maqluba", "🍚🍆🍗🔄", "Palestinian 'upside-down' pot of rice, fried vegetables and chicken, flipped onto a platter.", ["maqlooba", "maqloubeh", "makluba", "maqlouba"]],
    ["musakhan", "Musakhan", "🐔🧅🫓", "Palestinian roast chicken on taboon bread with heaps of onions and sumac.", ["msakhan"]],
    ["kibbeh", "Kibbeh", "🏈🥩🌰", "Torpedo-shaped croquettes of bulgur shell and spiced minced lamb.", ["kibbe", "kebbeh", "kubba", "kubbeh"]],
    ["mujaddara", "Mujaddara", "🍚🧅🥄", "Lentils and rice topped with deeply caramelised onions.", ["mujadara", "mejadra", "mujaddarah", "mujadarah"]],
    ["labneh", "Labneh", "🥛🫒🌿", "Thick strained yogurt spread with olive oil and herbs.", ["labne", "labaneh", "labna"]],
    ["muhammara", "Muhammara", "🌶️🥜🫓", "Syrian roasted red pepper and walnut dip.", ["mhammara"]],
    ["shish-taouk", "Shish taouk", "🍢🐔🧄", "Lebanese marinated chicken skewers served with garlic sauce.", ["shish tawook", "shish tawouk", "shish tauk", "taouk", "tawook"]],
    ["kabsa", "Kabsa", "🍗🍚🍋🌰", "Saudi spiced rice with chicken, dried lime and toasted nuts.", ["kabsah", "machboos", "majboos"]],
    ["mandi", "Mandi", "🍖🍚🕳️", "Yemeni meat and rice cooked in an underground pit oven.", ["lamb mandi", "chicken mandi"]],
    ["luqaimat", "Luqaimat", "⚪🍯🌴", "Gulf crispy fried dough balls drizzled with date syrup.", ["lugaimat", "lokma"]],
    ["turkish-delight", "Turkish delight", "🍬🌹", "Chewy cubes of rosewater-scented gel dusted in icing sugar.", ["lokum", "rahat lokum"]],
    ["menemen", "Menemen", "🍳🫑🍅🧅", "Turkish soft-scrambled eggs cooked with peppers, tomato and onion."],
    ["lahmacun", "Lahmacun", "🫓🥩🍋", "Thin, crisp Turkish flatbread topped with spiced minced lamb, rolled up with lemon and parsley.", ["lahmajun", "turkish pizza"]],
    ["pide", "Pide", "🛶🧀🥚", "Boat-shaped Turkish flatbread baked with cheese, meat or egg.", ["turkish pide"]],
    ["iskender", "İskender kebab", "🥩🍅🥛🍞", "Bursa's thin rotisserie-meat slices on bread under tomato sauce, browned butter and yogurt.", ["iskender", "iskender kebap"]],
    ["manti", "Manti", "🥟🥛🌶️", "Tiny Turkish meat dumplings under garlicky yogurt and red pepper butter.", ["mantu"]],
    ["borek", "Börek", "🌀🧀🥬", "Flaky filo pastry rolls or pies filled with cheese, spinach or meat.", ["borek", "burek", "boreks"]],
    ["simit", "Simit", "🥯🫖", "Turkish sesame-crusted bread ring sold from street carts.", ["gevrek"]],
    ["imam-bayildi", "Imam bayildi", "🍆🧅🍅🫒", "Turkish aubergines stuffed with onion and tomato and braised in olive oil - 'the imam fainted'.", ["imam bayıldı", "imambayildi"]],
    ["dolma", "Dolma", "🍇🍃🍚", "Vine leaves rolled around rice, herbs and pine nuts.", ["dolmades", "dolmas", "stuffed vine leaves", "warak enab", "sarma"]],
    ["tahdig", "Tahdig", "🍚🟡🔥", "Persian crispy golden crust of rice from the bottom of the pot.", ["tah dig", "tahdiq"]],
    ["ghormeh-sabzi", "Ghormeh sabzi", "🌿🥩🍋", "Persian herb stew with kidney beans, lamb and dried limes.", ["khoresh ghormeh sabzi", "gormeh sabzi", "ghormeh sabzee"]],
    ["fesenjan", "Fesenjan", "🍗🌰🔴", "Persian stew of chicken in a sweet-sour pomegranate and walnut sauce.", ["fesenjoon", "khoresh fesenjan", "fesenjun"]],
    ["joojeh-kabab", "Joojeh kabab", "🐔🍋🟡", "Persian saffron-and-lemon chicken kebabs.", ["jujeh kabab", "joojeh kebab", "jujeh kabob", "joojeh"]],
    ["chelo-kebab", "Chelo kebab", "🍚🍢🍅", "Iran's national dish: grilled minced-meat kebab on fluffy saffron rice with charred tomato.", ["chelow kabab", "koobideh", "kabab koobideh", "kebab koobideh", "chelo kabab"]],
    ["ash-reshteh", "Ash reshteh", "🍜🥬🥛", "Thick Persian noodle soup with herbs, beans and fermented whey.", ["ash-e reshteh", "aash reshteh", "ash e reshteh"]],
    ["masgouf", "Masgouf", "🐟🔥🍋", "Iraq's butterflied river carp, slow-grilled beside an open fire.", ["masguf", "masgoof"]],
    ["sabich", "Sabich", "🍆🥚🥙", "Pitta stuffed with fried aubergine, hard-boiled egg and tahini, an Israeli favourite.", ["sabih"]],
    ["malabi", "Malabi", "🍮🌹🥜", "Rosewater milk pudding topped with syrup and chopped pistachios.", ["muhallebi", "mahalabia", "muhallabia", "mahalabiya"]],
    ["halva", "Halva", "🟫🌰🍯", "Dense, crumbly sweet made from sesame paste and sugar.", ["halvah", "helva", "halwa"]],
    ["mercimek", "Mercimek çorbası", "🥣🍋🌶️", "Velvety Turkish soup of puréed red lentils with lemon and chilli butter.", ["mercimek corbasi", "mercimek", "turkish lentil soup", "red lentil soup", "lentil soup"]],
    ["fatteh", "Fatteh", "🫓🥣🥛", "Layers of toasted bread, chickpeas and garlicky yogurt topped with pine nuts.", ["fatteh hummus", "fatta", "fattet hummus", "fattah"]],
    ["maamoul", "Maamoul", "🍪🌴🥜", "Shortbread cookies filled with dates or nuts, baked for Eid and Easter.", ["mamoul", "ma'amoul", "maamool"]],
    ["doner", "Döner kebab", "🥙🥩🔥", "Turkish layered meat roasted on a vertical spit and shaved into bread - Germany's favourite late-night snack.", ["doner", "döner", "doner kebap", "donair"]],
    ["gozleme", "Gözleme", "🥞🧀🥬", "Turkish thin folded flatbread stuffed with spinach and cheese, cooked on a griddle.", ["gozleme"]],
    ["qatayef", "Qatayef", "🥞🌙🧀", "Ramadan pancakes folded around cream or nuts, then fried or drizzled with syrup.", ["atayef", "katayef", "qatayif"]],
    ["kousa-mahshi", "Kousa mahshi", "🥒🍚🍅", "Courgettes hollowed out, stuffed with spiced rice and meat, and simmered in tomato.", ["kusa mahshi", "kousa mahshe", "stuffed courgettes", "stuffed zucchini"]],
    ["ouzi", "Ouzi", "🐑🍚🥜", "Whole roast lamb on spiced rice with nuts and raisins, a Gulf feast.", ["quzi", "oozie", "lamb ouzi"]],
  ],
};
